### ISSUE TITLE
Pima Hunter Pro 144 - Exception after arming - Not enough data in channel

### ISSUE THREAD

**Issue by efic1** [deiger/Alarm#18]
Hi,
I'm trying to set up the home assistant pima integration and I'm getting the below exception every-time I'm trying to arm the alarm. note that the alarm is actually arming but the script is stuck after this exception.

I'm connecting using the MWA500 Module.

E0424 19:15:47.115  pima_server.py:116] Exception raised by Alarm.
Traceback (most recent call last):
  File "pima_server.py", line 104, in run
    status = self._alarm.get_status()  # type: pima.Status
  File "/app/pima.py", line 179, in get_status
    response = self._read_message()
  File "/app/pima.py", line 295, in _read_message
    self._make_hex(data), length + 3))
pima.Error: Not enough data in channel: 7a 13 05 01 02 00 00 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 should have 125 bytes.
I0424 19:15:47.119  pima_server.py:119] Trying to create the Alarm anew.
I0424 19:15:49.231  pima.py:181] Exception: GarbageInputError('Garbage (0)!').

**Comment by mizrachiran** [comment]
@efic1 I have the same issue on the initial connection, did you solve it?
