### ISSUE TITLE
Error "Not enough data in channel" on script start

### ISSUE THREAD

**Issue by mizrachiran** [deiger/Alarm#28]
Hi,

Trying to setup my Hunter Pro system using a wifi to serial module.
I receive the following error on start:

`raise Error('Not enough data in channel: {} should have {} bytes.'.format( pima.Error: Not enough data in channel: db 43 4d 3d 34 31 43 37 42 43 41 36 30 41 41 39 39 46 36 30 30 30 37 34 39 36 20 20 20 20 20 a4 b7 b2 a6 a0 20 ba ab b8 b2 ae 48 50 31 34 34 20 49 4c 20 68 65 20 37 2e 30 32 30 39 34 38 35 30 b2 29 dc should have 222 bytes.`

Here is the data that return from the system:
`b'\xdbCM=41C7BCA60AA99F60007496 \xa4\xb7\xb2\xa6\xa0 \xba\xab\xb8\xb2\xaeHP144 IL he 7.02094850\xb2)\xdc'
`

Would appreciate any kind of assistance!
Thanks

**Comment by alws34** [comment]
HI! 
i get the exact same issue while arming the alarm via home assistnat
E0422 16:08:23.055  pima_server.py:116] Exception raised by Alarm.
                                        Traceback (most recent call last):
                                          File "/usr/lib/pima/pima_server.py", line 104, in run
                                            status = self._alarm.get_status()  # type: pima.Status
                                          File "/usr/lib/pima/pima.py", line 179, in get_status
                                            response = self._read_message()
                                          File "/usr/lib/pima/pima.py", line 289, in _read_message
                                            raise Error('Not enough data in channel: {} should have {} bytes.'.format(
                                        pima.Error: Not enough data in channel: 62 0d 05 01 02 00 00 04 00 00 00 01 00>...


the alarm does arm, but i lose control over it immediately after arming, so i must turn it off manually (or it will start alarming..).
Also,  the commands are very slow (from pressing "arm" to actual arm, there is a substantial amount of time)

**Comment by mizrachiran** [comment]
@deiger I would appreciate your support
