### ISSUE TITLE
Exception raised by Alarm - often failure of communication

### ISSUE THREAD

**Issue by ohadlevy** [deiger/Alarm#30]
Hello,

Thank you for the project...

after a few minutes/hours I often see in the logs the following:

docker logs addon_b5dcdcba_pima 
```
E1117 11:00:47.924  pima_server.py:116] Exception raised by Alarm.
Traceback (most recent call last):
  File "/app/pima_server.py", line 104, in run
    status = self._alarm.get_status()  # type: pima.Status
  File "/app/pima.py", line 179, in get_status
    response = self._read_message()
  File "/app/pima.py", line 294, in _read_message
    raise Error('Invalid input on channel, CRC for {} is {}, not {}!'.format(
pima.Error: Invalid input on channel, CRC for 01 00 is 36865, not 0!
E1117 11:00:48.951  pima_server.py:122] Failed to recreate Alarm object. Exit for a clean restart.
Traceback (most recent call last):
  File "/app/pima_server.py", line 104, in run
    status = self._alarm.get_status()  # type: pima.Status
  File "/app/pima.py", line 179, in get_status
    response = self._read_message()
  File "/app/pima.py", line 294, in _read_message
    raise Error('Invalid input on channel, CRC for {} is {}, not {}!'.format(
pima.Error: Invalid input on channel, CRC for 01 00 is 36865, not 0!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pima_server.py", line 120, in run
    self._create_alarm()
  File "/app/pima_server.py", line 155, in _create_alarm
    self._status = self._alarm.get_status()  # type: pima.Status
  File "/app/pima.py", line 179, in get_status
    response = self._read_message()
  File "/app/pima.py", line 289, in _read_message
    raise Error('Not enough data in channel: {} should have {} bytes.'.format(
pima.Error: Not enough data in channel: 46 76 01 a9 21 62 0d 05 01 02 00 00 00 00 00 00 01 00 00 00 03 00 0b 0f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 05 should have 73 bytes.
E1117 11:00:48.971  pima_server.py:116] Exception raised by Alarm.
Traceback (most recent call last):
  File "/app/pima_server.py", line 104, in run
    status = self._alarm.get_status()  # type: pima.Status
  File "/app/pima.py", line 179, in get_status
    response = self._read_message()
  File "/app/pima.py", line 294, in _read_message
    raise Error('Invalid input on channel, CRC for {} is {}, not {}!'.format(
pima.Error: Invalid input on channel, CRC for 00 is 0, not 1285!
E1117 11:00:49.008  pima_server.py:122] Failed to recreate Alarm object. Exit for a clean restart.
Traceback (most recent call last):
  File "/app/pima_server.py", line 104, in run
    status = self._alarm.get_status()  # type: pima.Status
  File "/app/pima.py", line 179, in get_status
    response = self._read_message()
  File "/app/pima.py", line 294, in _read_message
    raise Error('Invalid input on channel, CRC for {} is {}, not {}!'.format(
pima.Error: Invalid input on channel, CRC for 00 is 0, not 1285!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/pima_server.py", line 120, in run
    self._create_alarm()
  File "/app/pima_server.py", line 155, in _create_alarm
    self._status = self._alarm.get_status()  # type: pima.Status
  File "/app/pima.py", line 179, in get_status
    response = self._read_message()
  File "/app/pima.py", line 294, in _read_message
    raise Error('Invalid input on channel, CRC for {} is {}, not {}!'.format(
pima.Error: Invalid input on channel, CRC for 05 05 05 05 00 00 is 39132, not 0!
E1117 11:00:49.036  pima_server.py:116] Exception raised by Alarm.
Traceback (most recent call last):
  File "/app/pima.py", line 179, in get_status
    response = self._read_message()
  File "/app/pima.py", line 287, in _read_message
    raise GarbageInputError('Garbage ({})!'.format(length))
pima.GarbageInputError: Garbage (0)!
```

restart seems to resolve it for a bit, but eventually it happens again after a few minutes..

happy for any guidance on how to debug.

**Comment by ohadlevy** [comment]
this seems to happen when the update rate is high, i lowered it to 5 seconds and it seems to be more stable, sadly misses a few events

**Comment by maorcc** [comment]
Why can't it recover from this state without restarting the service?

**Comment by ohadlevy** [comment]
@maorcc looking at the trace, it looks like nested exception (exception within exception)?

**Comment by ohadlevy** [comment]
I can confirm that the issue is fixed by https://github.com/deiger/Alarm/pull/31.

@deiger could you please take a look? thanks
